development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: ontrack_be_production
  origins:
    - http://localhost:5000
    - https://ontrack-fe-4b819560ba35.herokuapp.com
    - http://ontrack-fe-4b819560ba35.herokuapp.com
